-- =========================================================
-- 1. CREATE SCHEMAS
-- =========================================================

CREATE SCHEMA IF NOT EXISTS student;
CREATE SCHEMA IF NOT EXISTS academics;


-- =========================================================
-- 2. STUDENT ID SEQUENCE
-- Generates IDs such as UNT_2025_0001
-- =========================================================

CREATE SEQUENCE IF NOT EXISTS student.students_unt_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


-- =========================================================
-- 3. STUDENTS TABLE
-- =========================================================

CREATE TABLE IF NOT EXISTS student.students_unt (
    student_id VARCHAR(30)
        DEFAULT (
            'UNT_2025_' ||
            LPAD(
                NEXTVAL(
                    'student.students_unt_student_id_seq'
                )::TEXT,
                4,
                '0'
            )
        ),

    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(200),
    course VARCHAR(100),
    age INTEGER,
    student_join_year INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    address TEXT,
    start_date DATE,
    end_date DATE,

    CONSTRAINT students_pkey
        PRIMARY KEY (student_id),

    CONSTRAINT students_email_unique
        UNIQUE (email),

    CONSTRAINT students_age_check
        CHECK (age IS NULL OR age > 0)
);


-- Connect the sequence to the student table.
-- PostgreSQL can manage the sequence as part of this table.

ALTER SEQUENCE student.students_unt_student_id_seq
    OWNED BY student.students_unt.student_id;


-- =========================================================
-- 4. COURSES TABLE
-- =========================================================

CREATE TABLE IF NOT EXISTS academics.courses (
    course_id VARCHAR(20) NOT NULL,
    course_name VARCHAR(100) NOT NULL,
    credits INTEGER NOT NULL,

    CONSTRAINT courses_pkey
        PRIMARY KEY (course_id),

    CONSTRAINT courses_credits_check
        CHECK (credits > 0)
);


-- =========================================================
-- 5. INSTRUCTORS TABLE
-- =========================================================

CREATE TABLE IF NOT EXISTS academics.instructors (
    instructor_id VARCHAR(20) NOT NULL,
    instructor_name VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,

    CONSTRAINT instructors_pkey
        PRIMARY KEY (instructor_id)
);


-- =========================================================
-- 6. ENROLLMENTS TABLE
-- =========================================================

CREATE TABLE IF NOT EXISTS academics.enrollments (
    enrollment_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY,

    student_id VARCHAR(30) NOT NULL,
    course_id VARCHAR(20) NOT NULL,
    enrollment_date DATE NOT NULL,

    CONSTRAINT enrollments_pkey
        PRIMARY KEY (enrollment_id),

    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES student.students_unt(student_id),

    CONSTRAINT fk_enrollment_course
        FOREIGN KEY (course_id)
        REFERENCES academics.courses(course_id)
);


-- =========================================================
-- 7. COURSE-INSTRUCTOR MAPPING TABLE
-- Creates the many-to-many relationship
-- =========================================================

CREATE TABLE IF NOT EXISTS academics.course_instructors (
    course_id VARCHAR(20) NOT NULL,
    instructor_id VARCHAR(20) NOT NULL,

    CONSTRAINT course_instructors_pkey
        PRIMARY KEY (course_id, instructor_id),

    CONSTRAINT fk_course_instructor_course
        FOREIGN KEY (course_id)
        REFERENCES academics.courses(course_id),

    CONSTRAINT fk_course_instructor_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES academics.instructors(instructor_id)
);