"""create initial database structure

Revision ID: a91826dbf5ff
Revises: 
Create Date: 2026-07-29 16:07:49.067308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91826dbf5ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_instructors',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('instructor_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('course_id', 'instructor_id'),
    schema='academics'
    )
    op.create_table('courses',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    schema='academics'
    )
    op.create_table('instructors',
    sa.Column('instructor_id', sa.String(), nullable=False),
    sa.Column('instructor_name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('instructor_id'),
    schema='academics'
    )
    op.create_table('students_unt',
    sa.Column('student_id', sa.String(), server_default=sa.text("'UNT_2025_' || LPAD(nextval('student.students_unt_student_id_seq')::TEXT, 4, '0')"), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('student_join_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    schema='student'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_unt', schema='student')
    op.drop_table('instructors', schema='academics')
    op.drop_table('courses', schema='academics')
    op.drop_table('course_instructors', schema='academics')
    # ### end Alembic commands ###
